# Title:        End-to-End-Sign-Language-AI-Translation-System
# Description:  End-to-end system for sign language translation using AI models across Edge and Cloud.
# Licence:      GNU GENERAL PUBLIC LICENSE
#
# If you are using any ideas, algorithms, packages, codes, datasets, workload, results, and plots included in this project, please cite
# the following paper:
#
# Nada Shahin and Leila Ismail, "Towards Trustworthy Sign Language Translation System:
# A Privacy-Preserving Edge–Cloud–Blockchain Approach", Mathematics 2025
# https://doi.org/10.3390/math13233759

# Transformer configuration
batch_size: 32
max_video_length: 300    # placeholder; real value comes from dataset

max_gloss_length: 27     # placeholder; real value comes from dataset
max_text_length: 30      # placeholder; real value comes from dataset

gloss_vocab_size: 835    # placeholder; real value comes from dataset
text_vocab_size: 914     # placeholder; real value comes from dataset

embed_dim: 512
encoder_layers: 1
decoder_layers: 1
hidden_units: 8
num_heads: 8

dropout_rate: 0.1
learning_rate: 5.0e-5
epochs: 30
